<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Character\Module'                        => __DIR__ . '/Module.php',
    'Character\Controller\CharacterController' => __DIR__ . '/src/Character/Controller/CharacterController.php',
    'CharacterTest\Framework\TestCase'        => __DIR__ . '/tests/Character/Framework/TestCase.php',
    'CharacterTest\SampleTest'                => __DIR__ . '/tests/Character/SampleTest.php',
);
