<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Charles Brown-Roberts'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <link href="//netdna.bootstrapcdn.com/bootswatch/3.1.0/flatly/bootstrap.min.css" rel="stylesheet">                

        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css') ?>
                        
        
                       



        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
		                

    </head>
    <body>
           
      <a class="sr-only" href="#content">Skip to main content</a>

    <!-- Docs master nav -->
    <header class="navbar navbar-static-top bs-docs-nav" id="top" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="../" class="navbar-brand">CharlesBrownRoberts.com</a>
    </div>
    <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
      <ul class="nav navbar-nav">
        <li>
          <a href="../getting-started">About</a>
        </li>
        <li class="active">
          <a href="../css">Portfolio</a>
        </li>
        <li>
          <a href="http://www.californiavol.com/blog">Blog</a>
        </li>
        <li>
          <a href="../javascript">Resume</a>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="http://expo.getbootstrap.com" onclick="_gaq.push(['_trackEvent', 'Navbar', 'Community links', 'Expo']);">Download Resume PDF</a></li>
      </ul>
    </nav>
  </div>
</header>


    <!-- Page layout -->
    <div class="bs-docs-header" id="content">
      <div class="container">
        <h1>Charles Brown-Roberts</h1>
        <p>PHP Web Developer, Web Accessibility Specialist, Front-End UI</p>
        <p><em>Everything you do is you</em></p>
        <p><button type="button" class="btn btn-success">Download Resume</button> <button type="button" class="btn btn-success">Contact Me</button></p>
        <div id="carbonads-container"><div class="carbonad"><script src="//platform.linkedin.com/in.js" type="text/javascript"></script>
<script type="IN/MemberProfile" data-id="http://www.linkedin.com/pub/charles-brown-roberts/32/547/303" data-format="inline" data-related="false"></script></div></div>
 <?php echo $this->content; ?>
      </div>
    </div>

	<div class="container">
		<div class="row">
			<div class="col-sm-4">
				<div class="well">
					<h3>Latest Projects</h3>
					<ul>
						<li>Streaming Video</li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
					</ul>
				</div>
			</div>
			<div class="col-sm-4">
				<div class="well">
					<h3>Latest Fiddles</h3>
					<ul>
						<li>item</li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
					</ul>
				</div>
			</div>			
			<div class="col-sm-4">
				<div class="well">
					<h3>Latest Tweets</h3>
					<ul>
						<li>item</li>
						<li></li>
						<li></li>
						<li></li>
						<li></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
  







    <!-- Footer
================================================== -->
<footer class="bs-docs-footer" role="contentinfo">
  <div class="container">
    <div class="bs-docs-social">
  <ul class="bs-docs-social-buttons">
    <li class="follow-btn">
      <a href="https://twitter.com/californiavol" class="twitter-follow-button" data-link-color="#0069D6" data-show-count="true">Follow @californiavol</a>
    </li>
    <li class="tweet-btn">
      <a href="https://twitter.com/share" class="twitter-share-button" data-url="http://getbootstrap.com/" data-count="horizontal" data-via="twbootstrap" data-related="mdo:Creator of Bootstrap">Tweet</a>
    </li>
  </ul>
</div>


    <p>Copyright 2014 Charles Brown-Roberts</p>
    <ul class="bs-docs-footer-links muted">
      <li><a href="../about/">About</a></li>
      <li>&middot;</li>
      <li><a href="../getting-started/#examples">Portfolio</a></li>
      <li>&middot;</li>
      <li><a href="http://www.californiavol.com/blog">Blog</a></li>
      <li>&middot;</li>
      <li><a href="https://github.com/californiavol">GitHub</a></li>
      <li>&middot;</li>
      <li><a href="../getting-started/#examples">Resume</a></li>
    </ul>
  </div>
</footer>
     
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>   
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>  
     
<script src="http://getbootstrap.com/assets/js/docs.min.js"></script>     
     
        <?php echo $this->inlineScript() ?>
        
        
        
        
        
    </body>
</html>
