<strong>Module:</strong>        Character &raquo;
<strong>Controller:</strong>    Character &raquo;
<strong>Action:</strong>        list

 <div class="container-fluid">
        <h1>My Characters</h1>

        <ul>
	        <li><a href="/character/character/character">Astiran</a></li>
	        <li>Vol</li>
	        <li>Elrewien</li>
	        <li>Sundel</li>
	        <li>Elron</li>
	        <li>Farandel</li>
	        	        
        </ul>
    </div>
