 <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container-fluid">
                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>

                </button>
                <a class="brand" href="#">DnD Characters Portfolio</a>
                <div class="nav-collapse collapse">
                    <ul class="nav">
                        <li class="active">
                            <a href="#">Home</a>
                        </li>
                        <li>
                            <a href="#list">Character List</a>
                        </li>
                        <li>
                            <a href="#add">Add Character</a>
                        </li>
                    </ul>
                </div>
                <!--/.nav-collapse -->
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <h1>Astiran</h1>

        <p>Use this document as a way to quick start any new project.
            <br>All you get is this message and a barebones HTML document.</p>
    </div>
    <!-- /container -->